src/App.tsx
src/components/MainScreen.tsx
src/pages/Routers.tsx

- 관련 이슈 #1 
- close #
<br>
라우팅 (App.tsx  -> Page/Routers.tsx)
<br>
<br>
- 링크, 관련 자료 등
<br>

[#1] chore: 라우팅 정리 및 배경 색 변경

---

src/components/MainScreen.tsx
src/components/MeetingRandom/Help/Help.tsx
src/components/MeetingRandom/Help/Styles.ts
src/components/MeetingRandom/JoinButton/JoinRandomMeetingButton.tsx
src/components/MeetingRandom/JoinButton/Styles.ts
src/components/MeetingRandom/MakeTeamBox/MakeTeamBox.tsx
src/components/MeetingRandom/MakeTeamBox/Styles.ts
src/components/MeetingRandom/TypeButton/Styles.ts
src/components/MeetingRandom/TypeButton/TypeButton.tsx
src/pages/MeetingRandom/MeetingRandom.tsx
src/pages/MeetingRandom/Styles.ts

- 관련 이슈 #9 
- close #
<br>
- 팀 랜덤 퍼블리싱
<br>
<br>
- 링크, 관련 자료 등
<br>

[#9] feat: 랜덤매칭  퍼블리싱

---

src/components/MeetingRandom/MakeTeamBox/Styles.ts
src/components/MeetingRandom/TypeButton/Styles.ts

- 관련 이슈 #9 
- close #
<br>
- E5E5E5 -> F2F2F2
<br>
<br>
- 링크, 관련 자료 등
<br>

[#1] design: 색변경(F2F2F2)

---

.gitignore
package-lock.json
package.json
public/index.html
src/App.tsx

- Amplitude 분석 툴 세팅
- 관련 이슈
- close #13 
<br>
- Amplitude API KEY 연결
- Dev/Test, Production 환경 변수 설정
- logEvent 테스트 완료
<br>
<br>

Feat/#13 Amplitude 데이터 분석 툴 연결 및 세팅

---

package-lock.json
src/components/MeetingRandom/Help/Help.tsx
src/components/MeetingRandom/Help/Styles.ts
src/components/MeetingRandom/JoinButton/JoinRandomMeetingButton.tsx
src/components/MeetingRandom/JoinButton/Styles.ts
src/components/MeetingRandom/MakeTeamBox/MakeTeamBox.tsx
src/components/MeetingRandom/MakeTeamBox/Styles.ts
src/pages/MeetingRandom/MeetingRandom.tsx
src/pages/MeetingRandom/MeetingRoading/MeetingRoading.tsx
src/pages/MeetingRandom/MeetingRoading/Styles.ts
src/pages/Routers.tsx

- 관련 이슈 #16 
- close #
<br>
- 미팅 로딩 중 퍼블리싱
<br>
<br>

[#16] feat: 미팅 로딩 퍼블리싱

---

package-lock.json
package.json
src/components/MainScreen.tsx
src/components/NavigationBar/NavigationBar.jsx
src/components/NavigationBar/Styles.js

-  네비게이션 바 제작
- 관련 이슈 #22 
- close #22 
<br>
- 네비게이션 바 제작
<br>

[#22] feat: 네비게이션바 제작

---

src/components/Booth/Header/Styles.ts
src/components/Booth/TypeButton/Styles.ts
src/components/BoothDetail/ItemInventory/Styles.ts
src/components/MainScreen.tsx
src/components/MeetingRandom/Help/Styles.ts
src/components/MeetingRandom/JoinButton/Styles.ts
src/components/MeetingRandom/MakeTeamBox/Styles.ts
src/components/MeetingRandom/Modal/Modal.tsx
src/components/MeetingRandom/Modal/Styles.ts
src/components/MeetingRandom/TypeButton/Styles.ts
src/components/NavigationBar/Styles.js
src/pages/MeetingRandom/Styles.ts

- ex) 네비게이션 바
- 관련 이슈 #22 
- close #22 
<br>
- 네비게이션 바 수정 및 반응형 수정
<br>

[#22] refactor : 네비게이션바 수정 및 반응형 수정

---

src/components/Booth/Booths/Styles.ts
src/components/BoothDetail/Explanation/Explanation.tsx
src/components/BoothDetail/Explanation/Styles.ts
src/components/BoothDetail/ItemInventory/Styles.ts
src/components/NavigationBar/Styles.js
src/pages/Booth/BoothDetail/Styles.ts

- ex) 화면 네비게이션 바 적용 및 사이즈 수정
- 관련 이슈 #35 
- close #35 
<br>
-화면 네비게이션 바 적용 및 사이즈 수정
<br>
<br>

[#35] fix : 화면 네비게이션 바 적용 및 사이즈 수정

---

src/pages/Authentication/Login/Styles.js

- ex) 로그인 페이지 화면 비율 수정
- 관련 이슈 #40 
- close #40 
<br>
- 로그인 페이지 화면 비율 수정
<br>
<br>

[#40]refactor : 로그인 페이지 화면 비율 수정

---

src/components/GotoMeeting/GotoMeeting.tsx
src/components/GotoMeeting/Styles.ts
src/pages/Booth/Booth.tsx
src/pages/Booth/BoothDetail/BoothDetail.tsx

- ex) 부스페이지에서 미팅 탭으로 라우팅버튼 제작
- 관련 이슈 #34 
- close #34
<br>
- 부스페이지에서 미팅 탭으로 라우팅버튼 제작
<br>
<br>
<br>

[#34] feat : 부스페이지에서 미팅 탭으로 라우팅버튼 제작

---

src/components/MeetingRandom/JoinButton/Styles.ts
src/components/MeetingRandom/MakeTeamBox/Styles.ts
src/components/MeetingRandom/TypeButton/Styles.ts
src/pages/MeetingRandom/MeetingRoading/Styles.ts
src/pages/MeetingRandom/Styles.ts

- ex) 부스 네비게이션 바
- 관련 이슈 #43 
- close #43 
<br>
- 부스 네비게이션 바
<br>

[#43] refactor: 부스 네비게이션 바

---

src/components/MainScreen.tsx
src/components/MeetingRandom/MakeTeamBox/MakeTeamBox.tsx
src/components/MeetingRandom/MakeTeamBox/Styles.ts
src/pages/MeetingRandom/Styles.ts

- ex) 네비게이션 바 모바일 화면 적용
- 관련 이슈 #43 
- close #
<br>
<br>
<br>
- 링크, 관련 자료 등
<br>

[#43] refactor:  네비게이션 바 모바일 화면 적용

---

src/components/MainScreen.tsx
src/components/NavigationBar/NavigationBar.jsx

- ex) 네비게이션 바 라우팅 수정
- 관련 이슈 #46 
- close #46 
<br>
- 네비게이션 바 라우팅 수정
<br>
<br>

[#48] feat : 네비게이션 바 라우팅 수정

---

src/pages/Authentication/Join/Join.jsx

- 회원가입 나이 범위 수정
- close #
<br>
- 회원가입 나이 범위 수정
<br>

[#51] feat: 회원가입 나이 범위 수정

---

src/components/Chatting/ChattingInventory/Teams/Styles.ts
src/components/Chatting/ChattingInventory/Teams/TeamData.tsx
src/components/Chatting/ChattingInventory/Teams/Teams.tsx
src/components/GotoMeeting/GotoMeeting.tsx
src/components/GotoMeeting/Styles.ts

- ex) 팀 없는 채팅 목록
- 관련 이슈 #53 
- close #53 
<br>
- 팀 없는 채팅 목록
<br>
<br>

[#53] feat: 팀 없는 채팅 목록

---

src/api/Chatting/chatingRoom/chatingRoom.ts
src/components/MainScreen.tsx
src/pages/Chatting/Chatting/Chatting.tsx
src/pages/Chatting/Chatting/Styles.ts

- ex) 채팅 기능 구현
- 관련 이슈 #54 
- close #54 
<br>
-채팅 기능 구현
<br>
<br>

[#54] feat: 채팅 기능 구현

---

src/pages/Authentication/Join/Styles.js

- 회원가입 페이지1 반응형 수정
<br>
- 회원가입 페이지1 반응형 수정
<br>

[#51] feat: 회원가입 페이지1 반응형 수정

---

src/pages/Authentication/Join/Join3.jsx
src/pages/Authentication/Join/Styles3.js
src/pages/Routers.tsx

- 회원가입 페이지3 틀 제작
<br>
- 회원가입 페이지3 틀 제작
<br>
<br>

[#51] feat: 회원가입 페이지3 틀 제작

---

src/api/booth/Getbooths.ts
src/components/Booth/Booths/Booths.tsx
src/index.tsx

- ex) api 두번 호출 방지
- close #101 
<br>
- api 두번 호출 방지
<br>

[#101] chore: api 두번 호출 방지

---

src/components/Meeting22/Team/Styles.js

2대2 페이지 디자인 수정사항
<br>
원 바꾸기
-이모지 수정 예정
<br>
<br>
<br>

[#50] refactor: 2대2 페이지 디자인 수정사항

---

src/components/MyPage/ModifyNickname/ModifyNickname.jsx
src/components/MyPage/ModifyNickname/Styles.js
src/pages/MyPage/ModifyEmoji.jsx/SelectEmoji.jsx
src/pages/MyPage/ModifyEmoji.jsx/StylesEmoji.js
src/pages/MyPage/ModifyProfile/ModifyProfile.jsx
src/pages/MyPage/ModifyProfile/Styles.js
src/pages/Routers.tsx

- 프로필 수정 페이지 퍼블리싱
- close #
<br>
- 프로필 수정 페이지 퍼블리싱
- 닉네임 변경 모달 제작
- 이모지 변경 페이지 제작
<br>
<br>

[#95] 프로필 수정 페이지 퍼블리싱

---

src/components/MyPage/Event/Styles.js
src/components/MyPage/QnA/Styles.js
src/pages/MyPage/MyPage/MyPage.jsx
src/pages/MyPage/MyPage/Styles.js

- 마이페이지 메인 ui 수정
- 관련 이슈
- close #
<br>
- 기존 오류 ui 수정
- ui 변경사항 업데이트 
<br>
<br>

[#93] 마이페이지 메인 ui 수정

---

src/api/axiosConfig.ts
src/api/booth/GetboothDetail.ts
src/api/booth/Getbooths.ts

- ex) api 구조 변경
- close #115
<br>
- api 구조 변경
- 반복되는 api 구조를 개선 
- axiosConfig파일에서 가져와서 header, baseUrl 반복해서 사용하는 코드 개선
<br>
<br>
- 링크, 관련 자료 등
<br>

[#115] refactor : api 구조 변경

---

src/assets/Icons.ts
src/assets/icon/navigationbar/Smyinformation.svg
src/components/NavigationBar/NavigationBar.jsx
src/components/NavigationBar/Styles.js
src/pages/MyPage/MyPage/Styles.js

- 관련 이슈 #122 
- close #122 
<br>
- 로고부터 스크롤되도록 수정 시 발생하는 네비게이션 바 위치 수정
- 마이페이지에 있을 경우 아이콘 검정색으로 변경
<br>

[#122] 마이페이지 네비게이션바 수정

---

src/pages/Authentication/Login/Login.jsx
src/pages/Authentication/Login/Styles.js
src/recoil/state/authAtom.js

- 관련 이슈 #108 
- close #108 
<br>
- 로그인 api 연결
<br>
<br>

[#108] 로그인 api 연결

---

src/api/Authentication/useLogin.js
src/components/NavigationBar/NavigationBar.jsx
src/pages/Authentication/Login/Login.jsx
src/pages/Meeting22/Meeting22.jsx
src/recoil/state/authState.js

- 관련 이슈 #134 
- close #
<br>
- api 컴포넌트화
- 리코일 파일명 수정 
<br>
<br>

[#134] 로그인 api 리팩토링

---

src/pages/Authentication/Join/Join2.jsx
src/pages/Authentication/Join/SelectEmoji.jsx
src/pages/Authentication/Join/Styles3.js
src/pages/Authentication/Join/StylesEmoji.js
src/pages/MyPage/ModifyEmoji.jsx/ModifyEmoji.jsx
src/pages/MyPage/ModifyEmoji.jsx/Styles.js
src/pages/MyPage/ModifyProfile/ModifyProfile.jsx
src/pages/MyPage/ModifyProfile/Styles.js
src/pages/Routers.tsx

- 관련 이슈 #136 
- close #136 
<br>
- 토스폰트 이모지로 수정
<br>

[#136] 토스폰트 이모지로 수정

---

package-lock.json
package.json
src/components/Meeting22/LoginPopUp/LoginPopUp.jsx
src/components/Meeting22/LoginPopUp/Styles.js
src/components/Meeting22/Team/Styles.ts
src/components/Meeting22/Team/Team.tsx
src/components/Meeting22/TeamBox/Styles.ts
src/components/Meeting22/TeamBox/TeamBox.tsx
src/components/Meeting22/TypeButton/Styles.ts
src/components/NavigationBar/Styles.js
src/data/NonLoginData.ts
src/pages/Meeting22/Meeting22.tsx
src/pages/Meeting22/Styles.ts

- ex) 팀 갤러리 ui 수정, 3대3 음악 변환 
- close #142 
<br>
- 팀 갤러리 ui 수정, 3대3 음악 변환 
<br>

[#142] refactor : 팀 갤러리 ui 수정, 3대3 음악 변환 

---

src/pages/Authentication/Join/Join.jsx
src/recoil/state/joinState.js

- 회원가입 전화번호 추가
- 관련 이슈 #161
- close #161
<br>
- 회원가입 전화번호 추가
<br>
<br>

[#161] 회원가입 전화번호 추가

---

src/api/Meeting/GetCheckDuplicate.ts
src/components/Meeting22/TeamMaking/TeamName/Styles.ts
src/components/Meeting22/TeamMaking/TeamName/TeamName.tsx

- ex) 팀명 중복 확인 api 연결
- 관련 이슈
- close #169 
<br>
- 팀명 중복 확인 api 연결
<br>
<br>

[#169]feat: 팀명 중복 확인 api 연결 

---

src/components/Common/Header/Header/Header.tsx
src/components/Common/Header/Header/Styles.ts
src/components/Common/Header/HeaderName/Header.tsx
src/components/Common/Header/HeaderName/Styles.ts

- ex) 공통 헤더 컴포넌트
- close #171
<br>
- 공통 헤더 컴포넌트
<br>

[#171]feat: 공통 헤더 컴포넌트

---

src/components/Meeting22/TeamMaking/Modal/TeamMemberModal.tsx
src/components/Meeting22/TeamMaking/TeamName/TeamName.tsx
src/recoil/type/TeamMaking/SearchTeamMember.ts

- ex) 검색 api 연결
- close #180 
<br>
- 검색 api 연결
<br>
<br>

[#180] feat: 검색 api 연결

---

src/pages/Authentication/Join/Join1/Join.jsx
src/pages/Authentication/Join/Join1/Styles.js
src/pages/Authentication/Join/Join2/Join2.jsx
src/pages/Authentication/Join/Join2/Styles.js

- 회원가입 정규식 추가
- 관련 이슈 #194 
- close #194 
<br>
- 회원가입 정규식 추가
<br>
<br>
- 링크, 관련 자료 등
<br>

[#194] 회원가입 정규식 추가

---

src/pages/Authentication/Join/Join1/Join.jsx
src/recoil/state/joinState.js

- 관련 이슈 #194 
- close #
<br>
- 회원가입 api전송 시 phoneNumber 추가
<br>

[#194] 회원가입 phoneNumber 추가

---

src/pages/MyPage/MyPage/MyPage.jsx
src/pages/MyPage/MyPage/Styles.js

- 마이페이지에 프로필수정페이지 연결
- 관련 이슈 #199 
- close #199 
<br>
- 마이페이지에 프로필수정페이지 연결
- LogoContainer 스타일 조정
<br>

[#199] 마이페이지에 프로필수정페이지 연결

---

src/components/MeetingRandom/MeetingRandomMain.tsx
src/pages/Notion/NotionMain.tsx
src/pages/Notion/Styles.ts
src/pages/Routers.tsx

- ex)노션 웹 뷰 공통 컴포넌트 제작
- close #204 
<br>
<br>
사용방법
Notion/NotionMain.ts에서 
case 의 url을 useNavigate로 사용하면 페이지 적용됨 
예시 
<br>
- 링크, 관련 자료 등
<br>

[#204] feat: 노션 웹 뷰 공통 컴포넌트 제작

---

src/components/Chatting/ChattingInventory/Teams/Styles.ts
src/components/Chatting/ChattingInventory/Teams/Teams.tsx
src/components/Common/Loading/Styles.ts
src/components/Common/Loading/loading.tsx

- ex) 로딩 ui 제작
- close #203
<br>
- 로딩 ui 제작
<br>
<br>

[#203] feat: 로딩 ui 제작

---

src/api/Chatting/GetacceptHi.ts
src/components/TeamIntro/Modal/SendQuestion/SendQuestion.tsx
src/pages/TeamIntro/TeamIntro.tsx

- ex) 아이디 채팅방에 추가 api 연결
- close #213
<br>
- 아이디 채팅방에 추가 api 연결
<br>
<br>

[#213] feat: 아이디 채팅방에 추가 api 연결

---

src/pages/MyPage/ModifyProfile/ModifyProfile.jsx
src/pages/MyPage/ModifyProfile/Styles.js
src/pages/MyPage/MyPage/MyPage.jsx
src/pages/MyPage/MyPage/Styles.js

- ex) 마이 로딩화면 추가
- 관련 이슈 #218 
- close #218 
<br>
- 마이 로딩화면 추가
<br>
<br>

[#218] 마이 로딩화면 추가

---

src/pages/MyPage/ModifyProfile/Styles.js
src/pages/MyPage/MyPage/Styles.js

- ex)  로딩 크기 수정
- 관련 이슈 #218 
- close #218
<br>
-  로딩 크기 수정
<br>

[#218] 로딩 크기 수정

---

package-lock.json
package.json
src/components/MyPage/ModalLogout/ModalLogout.jsx
src/components/MyPage/ModalLogout/Styles.js
src/components/MyPage/ModalWithdraw/ModalWithdraw.jsx
src/components/MyPage/ModalWithdraw/Styles.js
src/pages/MyPage/MyPage/MyPage.jsx
src/pages/MyPage/MyPage/Styles.js

- 로그아웃, 회원탈퇴 모달 퍼블리싱
- 관련 이슈 #220 
- close #220 
<br>
- 로그아웃 모달 퍼블리싱
- 회원탈퇴 모달 퍼블리싱
<br>
<br>

[#220] 로그아웃, 회원탈퇴 모달 퍼블리싱

---

src/components/Chatting/Chat/Sidebar/ChatSidebar.tsx
src/components/Chatting/ExitModal/ExitModal.tsx
src/components/Chatting/ExitModal/Styles.ts
src/components/Chatting/ReceiveHi/Teams/Teams.tsx
src/components/Common/Profile/ProfileDetail/ProfileDetail.tsx
src/components/Common/Profile/ProfileDetail/Styles.ts
src/components/TeamMaking/Teams/Teams.tsx
src/pages/Chatting/Chatting/Chatting.tsx
src/pages/Chatting/UserDetail/ChatUserdetail.tsx
src/pages/Chatting/UserDetail/Styles.ts
src/pages/Routers.tsx

- ex)채팅 사용자 상세정보 가져오기 
- close #224 
<br>
<br>
<br>
- 링크, 관련 자료 등
<br>

[#224]feat: 채팅 사용자 상세정보 가져오기 

---

src/api/Chatting/PostRandomChatRoom.ts
src/api/Chatting/WebSocketchat.ts
src/api/Meeting/GetRandomTicket.ts
src/api/Meeting/GetRandomnow.ts
src/api/Meeting/WebRandom.ts
src/components/Chatting/Chat/Sidebar/ChatSidebar.tsx
src/components/MeetingRandom/JoinButton/JoinRandomMeetingButton.tsx
src/components/MeetingRandom/MakeTeamBox/MakeTeamBox.tsx
src/components/MeetingRandom/MeetingRandomMain.tsx
src/components/MeetingRandom/Modal/Modal.tsx
src/components/Non-member/Meeting/JoinButton/JoinRandomMeetingButton.tsx
src/components/Non-member/Meeting/JoinButton/Styles.ts
src/components/Non-member/Meeting/MakeTeamBox/MakeTeamBox.tsx
src/components/Non-member/Meeting/MakeTeamBox/Styles.ts
src/pages/Meeting22/Meeting22.tsx
src/pages/Meeting22/Styles.ts
src/pages/NonMember/Meeting/Meeting.tsx
src/pages/NonMember/Meeting/Styles.ts
src/recoil/type/Meeting/RandomNowType.ts

- ex) 랜덤미팅 소켓 및 api 연결 
- close #229 
<br>
- 랜덤미팅 소켓 및 api 연결 
<br>
<br>
- 링크, 관련 자료 등
<br>

[#229] feat: 랜덤미팅 소켓 및 api 연결 

---

src/api/Authentication/useLogin.js
src/api/Authentication/useLoginCheck.js
src/api/Authentication/useLogout.js
src/components/MyPage/ModalLogout/ModalLogout.jsx
src/recoil/state/authState.ts

- 관련 이슈 #228 
- close #228
<br>
- 로그아웃 api 연결
<br>

[#228] 로그아웃 api 연결

---

src/components/MyPage/ItemShop/ItemBanner/ItemBanner.jsx
src/components/MyPage/ItemShop/ItemBanner/Styles.js
src/components/MyPage/QnA/QnA.jsx
src/components/MyPage/QnA/Styles.js
src/pages/MyPage/ModifyEmoji/ModifyEmoji.jsx
src/pages/MyPage/ModifyEmoji/Styles.js
src/pages/MyPage/MyPage/MyPage.jsx

- 마이페이지 DOM 오류 수정
- 관련 이슈 #236 
- close #236 
<br>
<br>

[#236] 마이페이지 DOM 오류 수정

---

src/api/Authentication/useWithdraw.js
src/components/MyPage/ModalWithdraw/ModalWithdraw.jsx

- 회원탈퇴 api 연결
- 관련 이슈 #234 
- close #234
<br>
- 회원탈퇴 api 연결
<br>
<br>

[#234] 회원탈퇴 api 연결

---

src/api/Authentication/checkDuplicateNickname.js
src/api/Authentication/checkDuplicateNumber.js
src/pages/Authentication/Join/Join1/Join.jsx
src/pages/Authentication/Join/Join2/Join2.jsx

- 관련 이슈 #238
- close #
<br>
- 회원가입 중복확인 api 연결
<br>

[238] 회원가입 중복확인 api 연결

---

package-lock.json
package.json
public/OneSignalSDKWorker.js
public/index.html

- 백엔드 구현 불가로 인한 OneSignal Setting 제거
- 관련 이슈
- close #240 
<br>
- index.html OneSignal 세팅 제거
<br>

[#240] fix: OneSignal Setting 제거

---

src/api/Meeting/WebRandom.ts
src/components/Meeting22/Team/Team.tsx
src/components/MeetingRandom/MeetingRandomMain.tsx
src/components/MeetingRandom/Modal/Modal.tsx
src/components/MyPage/ModalWithdraw/ModalWithdraw.jsx
src/components/MyPage/QnA/QnA.jsx
src/pages/Meeting22/Meeting22.tsx
src/pages/MyPage/ModifyProfile/ModifyProfile.jsx
src/pages/MyPage/MyPage/MyPage.jsx
src/pages/NonMember/Meeting/Meeting.tsx
src/pages/TeamIntro/TeamIntro.tsx
src/pages/TeamMaking/TeamMaking.tsx

- Amplitude 마이, 미팅 트래킹 추가
- 관련 이슈
- close #251 
<br>
- 마이
- 미팅
<br>

[#251] Amplitude 마이, 미팅 트래킹 추가

---

src/components/Meeting22/TypeButton/TypeButton.tsx
src/pages/Meeting22/Meeting22.tsx
src/types/meetingTypes.ts

- 미팅 쿼리스트링 수정
- 관련 이슈
- close #297 
<br>
- 미팅 쿼리스트링 수정
<br>
<br>
- 링크, 관련 자료 등
<br>

[FIX] 미팅 쿼리스트링 수정

---

src/components/MeetingRandom/Help/Help.tsx
src/components/MeetingRandom/MakeTeamBox/MakeTeamBox.tsx
src/components/MeetingRandom/MeetingRandomMain.tsx

- 랜덤미팅 참여 시 바로 대기화면이 보이도록 렌더링
- 관련 이슈
- close #299 
<br>
- 랜덤미팅 참여 시 대기화면 렌더링
<br>
<br>
- 링크, 관련 자료 등
<br>

[REFACTOR] 랜덤미팅 참여 시 대기화면 렌더링

---

src/components/MeetingRandom/Help/Help.tsx
src/components/MeetingRandom/MakeTeamBox/MakeTeamBox.tsx
src/components/MeetingRandom/MeetingRandomMain.tsx

- 매칭 완료 후, 채팅 탭으로 이동
- 관련 이슈
- close #310 
<br>
- 매칭 완료 후, 채팅 탭으로 이동
<br>
<br>
- 링크, 관련 자료 등
<br>

[FIX] 랜덤미팅 채팅 탭
